"""
GitHub PR output — creates a branch and PR with the full risk report.

Requires:
  GITHUB_TOKEN: Personal Access Token with `repo` scope
  GITHUB_REPO: "org/repo-name"

PR contains:
  - Clause-by-clause risk table
  - Regulation citations
  - Redlined alternatives for medium/high/violation clauses
  - Contradiction and historical flag summaries
"""

import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def _build_pr_body(
    filename: str,
    job_id: str,
    risk_report: list[dict],
    redlines: list[dict],
    contradictions: list[dict],
    historical_flags: list[dict],
    duration_seconds: float,
) -> str:
    """Build the markdown body for the GitHub PR."""
    violation_count = sum(1 for c in risk_report if c.get("risk_level") == "violation")
    high_count = sum(1 for c in risk_report if c.get("risk_level") == "high")
    medium_count = sum(1 for c in risk_report if c.get("risk_level") == "medium")
    low_count = sum(1 for c in risk_report if c.get("risk_level") == "low")
    compliant_count = sum(1 for c in risk_report if c.get("risk_level") == "compliant")

    lines: list[str] = [
        f"# Contract Review: `{filename}`",
        f"> Auto-generated by HackArena AI | Job ID: `{job_id}` | "
        f"Analysis time: {duration_seconds:.1f}s | "
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## 📊 Risk Summary",
        "",
        "| Level | Count |",
        "|---|---|",
        f"| 🔴 Violation | **{violation_count}** |",
        f"| 🟠 High | **{high_count}** |",
        f"| 🟡 Medium | **{medium_count}** |",
        f"| 🟢 Low | {low_count} |",
        f"| ✅ Compliant | {compliant_count} |",
        f"| **Total clauses** | **{len(risk_report)}** |",
        "",
    ]

    if contradictions:
        lines += [
            "## ⚠️ Internal Contradictions Detected",
            "",
            f"**{len(contradictions)} contradiction(s) found across clauses in this document.**",
            "",
        ]
        for i, c in enumerate(contradictions, 1):
            lines += [
                f"### Contradiction {i} — Severity: `{c.get('severity', 'unknown').upper()}`",
                f"> **Clause A** (`{c.get('clause_a_id')}`): {c.get('clause_a_text', '')[:200]}",
                f">",
                f"> **Clause B** (`{c.get('clause_b_id')}`): {c.get('clause_b_text', '')[:200]}",
                "",
                f"**Conflict:** {c.get('explanation', '')}",
                "",
            ]

    if historical_flags:
        lines += [
            "## 🏴 Historically Flagged Clause Patterns",
            "",
            f"**{len(historical_flags)} clause(s) match patterns previously flagged in this organisation.**",
            "",
        ]
        for flag in historical_flags:
            lines += [
                f"- **Clause** `{flag.get('clause_id')}` matched a `{flag.get('original_risk_level', '')}` "
                f"risk pattern from project `{flag.get('flagged_in_project', '')}` "
                f"on {flag.get('flagged_date', '')}",
            ]
        lines.append("")

    lines += [
        "## 📋 Clause-by-Clause Analysis",
        "",
    ]

    # Group by risk level, highest first
    risk_order = ["violation", "high", "medium", "low", "compliant"]
    risk_emojis = {
        "violation": "🔴", "high": "🟠", "medium": "🟡",
        "low": "🟢", "compliant": "✅",
    }

    redline_map = {r["clause_id"]: r for r in redlines}

    for level in risk_order:
        level_clauses = [c for c in risk_report if c.get("risk_level") == level]
        if not level_clauses:
            continue
        emoji = risk_emojis.get(level, "")
        lines.append(f"### {emoji} {level.upper()} Risk Clauses ({len(level_clauses)})")
        lines.append("")

        for clause in level_clauses:
            cid = clause.get("clause_id", "")
            lines += [
                f"#### `{cid}` — {clause.get('clause_type', 'other').replace('_', ' ').title()}",
                "",
                f"**Original text:**",
                f"> {clause.get('text', '')[:500]}",
                "",
                f"**Regulation:** `{clause.get('regulation', 'N/A')}`  ",
                f"**Confidence:** `{clause.get('confidence', 0):.0%}`  ",
                f"**Risk:** {clause.get('explanation', '')}",
                "",
            ]
            if cid in redline_map:
                rl = redline_map[cid]
                lines += [
                    "<details><summary>📝 View Compliant Redline</summary>",
                    "",
                    f"> {rl.get('redlined_text', '')}",
                    "",
                    f"*{rl.get('explanation', '')}*",
                    "",
                    "</details>",
                    "",
                ]

    return "\n".join(lines)


async def create_github_pr(
    job_id: str,
    filename: str,
    risk_report: list[dict],
    redlines: list[dict],
    contradictions: list[dict],
    historical_flags: list[dict],
    duration_seconds: float,
    github_token: str,
    github_repo: str,
) -> str | None:
    """
    Create a GitHub branch + PR with the full contract risk report.

    Returns:
        PR URL string, or None if GitHub integration is not configured.
    """
    if not github_token or github_token.startswith("ghp_xxx"):
        logger.info("GitHub integration not configured — skipping PR creation")
        return None

    try:
        from github import Github, GithubException

        g = Github(github_token)
        repo = g.get_repo(github_repo)

        branch_name = f"contract-review/{job_id}"
        violation_count = sum(1 for c in risk_report if c.get("risk_level") == "violation")

        # Get default branch SHA
        default_branch = repo.default_branch
        ref = repo.get_git_ref(f"heads/{default_branch}")
        sha = ref.object.sha

        # Create branch
        try:
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sha)
            logger.info(f"GitHub: created branch '{branch_name}'")
        except GithubException as e:
            if "Reference already exists" in str(e):
                logger.warning(f"GitHub branch '{branch_name}' already exists, reusing")
            else:
                raise

        # Commit the risk report markdown
        report_path = f"reports/{job_id}/risk_report.md"
        report_content = _build_pr_body(
            filename=filename,
            job_id=job_id,
            risk_report=risk_report,
            redlines=redlines,
            contradictions=contradictions,
            historical_flags=historical_flags,
            duration_seconds=duration_seconds,
        )

        try:
            existing = repo.get_contents(report_path, ref=branch_name)
            repo.update_file(
                path=report_path,
                message=f"Update contract review: {filename}",
                content=report_content,
                sha=existing.sha,
                branch=branch_name,
            )
        except Exception:
            repo.create_file(
                path=report_path,
                message=f"Add contract review: {filename}",
                content=report_content,
                branch=branch_name,
            )

        # Create PR
        pr_title = (
            f"Contract Review: {filename} — "
            f"{violation_count} violation(s) found"
        )
        pr = repo.create_pull(
            title=pr_title,
            body=report_content[:65000],  # GitHub PR body limit
            head=branch_name,
            base=default_branch,
        )
        logger.info(f"GitHub PR created: {pr.html_url}")
        return pr.html_url

    except ImportError:
        logger.error("PyGithub not installed. Run: pip install PyGithub")
        return None
    except Exception as e:
        logger.error(f"GitHub PR creation failed: {e}")
        return None
